### ISSUE TITLE
Sign up as entrepreneur

### ISSUE THREAD

**Issue by irene-ng** [GoldenOwlAsia/Ideaburn#1]
UI:  [register.html](https://files.zenhub.io/56dd2f2593fd4909417cce04)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

Sign up as entrepreneur 
![image](https://cloud.githubusercontent.com/assets/16044171/13563172/f9c09536-e471-11e5-8ba7-cdf3267cc09a.png)

Field explained
![image](https://cloud.githubusercontent.com/assets/16044171/13563279/0a86306e-e473-11e5-8e96-60d7532966b6.png)

Sign up statement
![image](https://cloud.githubusercontent.com/assets/16044171/13563293/27035208-e473-11e5-9bbc-e412c2900eff.png)

**Comment by minhquan4080** [comment]
@irene-ng  please follow #12
