### ISSUE TITLE
Sign up as start up 

### ISSUE THREAD

**Issue by irene-ng** [GoldenOwlAsia/Ideaburn#2]
Sign up as a start up
![image](https://cloud.githubusercontent.com/assets/16044171/13563216/73144f22-e472-11e5-91cf-80bf1cd1c7d5.png)

Field explainer
![image](https://cloud.githubusercontent.com/assets/16044171/13563326/63e7233e-e473-11e5-8303-a8cff2d7c9e4.png)

Sign up statement
![image](https://cloud.githubusercontent.com/assets/16044171/13563232/9ec8b3f6-e472-11e5-99a9-3026efcd9879.png)

**Comment by minhquan4080** [comment]
@irene-ng  Please follow #12
