### ISSUE TITLE
Sign up as an investor

### ISSUE THREAD

**Issue by irene-ng** [GoldenOwlAsia/Ideaburn#3]
Fields: 
![image](https://cloud.githubusercontent.com/assets/16044171/13563779/42e7c086-e477-11e5-8eae-677add24af8b.png)

UI: 
[register.html](https://files.zenhub.io/56dd3b2993fd4909417ccf30)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

![image](https://cloud.githubusercontent.com/assets/16044171/13564143/fc7a95e4-e479-11e5-961f-7bdde76b8aff.png)

**Comment by minhquan4080** [comment]
@irene-ng please follow #12
