### ISSUE TITLE
[entrepreneur] overview page of entrepreneur

### ISSUE THREAD

**Issue by irene-ng** [GoldenOwlAsia/Ideaburn#35]
![ideaburn-dashboard-intreprenuerpage](https://cloud.githubusercontent.com/assets/16044171/13735848/0847e568-e9e1-11e5-859d-a08ef44d5ae7.jpg)
![ideaburn-home-enterprenuers-2](https://cloud.githubusercontent.com/assets/16044171/13735849/087412e6-e9e1-11e5-9735-cf9c38d331ba.jpg)

**Comment by irene-ng** [comment]
Please take reference from this hompage: http://ideaburn-goldenowl.herokuapp.com/ for header + footer.

**Comment by maggie1994** [comment]
done

**Comment by irene-ng** [comment]
+ Hiding linkedin link under the ava and communication tab ( only paid investor can see these part).
When click on Read more on entrepreneur page, only registered users can see this page, if they're not register, link to sign up page.
