### ISSUE TITLE
Sign in as entrepreneur/ start up/ investor

### ISSUE THREAD

**Issue by irene-ng** [GoldenOwlAsia/Ideaburn#4]
UI
[login.html](https://files.zenhub.io/56dd3dc493fd4909417ccf59)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by minhquan4080** [comment]
![signin ui](https://cloud.githubusercontent.com/assets/9989471/13597633/3e1c6568-e54c-11e5-9d01-dd9812cdd4f4.png)
