### ISSUE TITLE
[homepage] entrepreneur page loading

### ISSUE THREAD

**Issue by irene-ng** [GoldenOwlAsia/Ideaburn#41]
![click on entrepreneur startup investor](https://cloud.githubusercontent.com/assets/16044171/13804504/173d4450-eb80-11e5-95f3-7465fac2f2cc.png)
When user click on entrepreneur/startup/investor, there is animated effect of entrepreneur and the "Entrepreneur" page will be shown slowly. all the rest of the page will be blurred.
Apply for Start up and Investor page.

**Comment by maggie1994** [comment]
done

**Comment by irene-ng** [comment]
It should come slowly drop down and goes down with lazy loading with the background is blurred.

**Comment by maggie1994** [comment]
done
