### ISSUE TITLE
[Idea Dashboard] Set all the idea box have the same size. 

### ISSUE THREAD

**Issue by irene-ng** [GoldenOwlAsia/Ideaburn#67]
![ideaburns idea dashboard size default](https://cloud.githubusercontent.com/assets/16044171/13942671/8d5174d0-f027-11e5-8e7b-afb66e1c1fc3.png)
All the idea box should have same default size. Apply for avatar also, should have only 1 shape and 1 size.

Just take the 1st sentences in description to show it on Ideabox,

Read more button will be fixed display on right down corner of the idea box.

**Comment by maggie1994** [comment]
done
